//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHeroData")]
  public partial class MsgHeroData : global::ProtoBuf.IExtensible
  {
    public MsgHeroData() {}
    
    private ulong _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong account
    {
      get { return _account; }
      set { _account = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _action_point;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"action_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action_point
    {
      get { return _action_point; }
      set { _action_point = value; }
    }
    private int _diamand;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamand
    {
      get { return _diamand; }
      set { _diamand = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEquipData")]
  public partial class MsgEquipData : global::ProtoBuf.IExtensible
  {
    public MsgEquipData() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _equip_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip_id
    {
      get { return _equip_id; }
      set { _equip_id = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private bool _equipped;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"equipped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool equipped
    {
      get { return _equipped; }
      set { _equipped = value; }
    }
    private int _client_save_flag;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"client_save_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int client_save_flag
    {
      get { return _client_save_flag; }
      set { _client_save_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgIntPair")]
  public partial class MsgIntPair : global::ProtoBuf.IExtensible
  {
    public MsgIntPair() {}
    
    private int _number_1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number_1
    {
      get { return _number_1; }
      set { _number_1 = value; }
    }
    private int _number_2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number_2
    {
      get { return _number_2; }
      set { _number_2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"HeroErrorCode")]
    public enum HeroErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"no_error", Value=0)]
      no_error = 0
    }
  
}