//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dream_hero.proto
// Note: requires additional types generated from: common.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CMsgHeroInit")]
  public partial class S2CMsgHeroInit : global::ProtoBuf.IExtensible
  {
    public S2CMsgHeroInit() {}
    
    private message.MsgHeroData _hero;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public message.MsgHeroData hero
    {
      get { return _hero; }
      set { _hero = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CMsgHeroEquip")]
  public partial class S2CMsgHeroEquip : global::ProtoBuf.IExtensible
  {
    public S2CMsgHeroEquip() {}
    
    private readonly global::System.Collections.Generic.List<message.MsgEquipData> _equips = new global::System.Collections.Generic.List<message.MsgEquipData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<message.MsgEquipData> equips
    {
      get { return _equips; }
    }
  
    private bool _end;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool end
    {
      get { return _end; }
      set { _end = value; }
    }
    private bool _begin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"begin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool begin
    {
      get { return _begin; }
      set { _begin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CMsgEquipInit")]
  public partial class S2CMsgEquipInit : global::ProtoBuf.IExtensible
  {
    public S2CMsgEquipInit() {}
    
    private message.S2CMsgHeroEquip _equip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public message.S2CMsgHeroEquip equip
    {
      get { return _equip; }
      set { _equip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}