//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
// Note: requires additional types generated from: common.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _pwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAccountRequest")]
  public partial class RegisterAccountRequest : global::ProtoBuf.IExtensible
  {
    public RegisterAccountRequest() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _pwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAccountFaildACK")]
  public partial class RegisterAccountFaildACK : global::ProtoBuf.IExtensible
  {
    public RegisterAccountFaildACK() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private string _gate_ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gate_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gate_ip
    {
      get { return _gate_ip; }
      set { _gate_ip = value; }
    }
    private uint _gate_port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gate_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_port
    {
      get { return _gate_port; }
      set { _gate_port = value; }
    }
    private uint _user_account = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }
    private message.enumLoginResult _result = message.enumLoginResult.enumLoginResult_Success;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(message.enumLoginResult.enumLoginResult_Success)]
    public message.enumLoginResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _chartype = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chartype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chartype
    {
      get { return _chartype; }
      set { _chartype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGame")]
  public partial class LoginGame : global::ProtoBuf.IExtensible
  {
    public LoginGame() {}
    
    private uint _user_account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientExit")]
  public partial class ClientExit : global::ProtoBuf.IExtensible
  {
    public ClientExit() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumLoginResult")]
    public enum enumLoginResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_Success", Value=0)]
      enumLoginResult_Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_Fail", Value=1)]
      enumLoginResult_Fail = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_NameFail", Value=2)]
      enumLoginResult_NameFail = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_PwdFail", Value=3)]
      enumLoginResult_PwdFail = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_HaveLogin", Value=4)]
      enumLoginResult_HaveLogin = 4
    }
  
}