// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class MsgHeroData;
class MsgEquipData;
class MsgIntPair;

enum HeroErrorCode {
  no_error = 0
};
bool HeroErrorCode_IsValid(int value);
const HeroErrorCode HeroErrorCode_MIN = no_error;
const HeroErrorCode HeroErrorCode_MAX = no_error;
const int HeroErrorCode_ARRAYSIZE = HeroErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* HeroErrorCode_descriptor();
inline const ::std::string& HeroErrorCode_Name(HeroErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    HeroErrorCode_descriptor(), value);
}
inline bool HeroErrorCode_Parse(
    const ::std::string& name, HeroErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HeroErrorCode>(
    HeroErrorCode_descriptor(), name, value);
}
// ===================================================================

class MsgHeroData : public ::google::protobuf::Message {
 public:
  MsgHeroData();
  virtual ~MsgHeroData();

  MsgHeroData(const MsgHeroData& from);

  inline MsgHeroData& operator=(const MsgHeroData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgHeroData& default_instance();

  void Swap(MsgHeroData* other);

  // implements Message ----------------------------------------------

  inline MsgHeroData* New() const { return New(NULL); }

  MsgHeroData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgHeroData& from);
  void MergeFrom(const MsgHeroData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgHeroData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 account = 1;
  bool has_account() const;
  void clear_account();
  static const int kAccountFieldNumber = 1;
  ::google::protobuf::uint64 account() const;
  void set_account(::google::protobuf::uint64 value);

  // required uint32 level = 2;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // required string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 action_point = 4;
  bool has_action_point() const;
  void clear_action_point();
  static const int kActionPointFieldNumber = 4;
  ::google::protobuf::int32 action_point() const;
  void set_action_point(::google::protobuf::int32 value);

  // required int32 diamand = 5;
  bool has_diamand() const;
  void clear_diamand();
  static const int kDiamandFieldNumber = 5;
  ::google::protobuf::int32 diamand() const;
  void set_diamand(::google::protobuf::int32 value);

  // required int32 gold = 6;
  bool has_gold() const;
  void clear_gold();
  static const int kGoldFieldNumber = 6;
  ::google::protobuf::int32 gold() const;
  void set_gold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgHeroData)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_action_point();
  inline void clear_has_action_point();
  inline void set_has_diamand();
  inline void clear_has_diamand();
  inline void set_has_gold();
  inline void clear_has_gold();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 account_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::int32 action_point_;
  ::google::protobuf::int32 diamand_;
  ::google::protobuf::int32 gold_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgHeroData* default_instance_;
};
// -------------------------------------------------------------------

class MsgEquipData : public ::google::protobuf::Message {
 public:
  MsgEquipData();
  virtual ~MsgEquipData();

  MsgEquipData(const MsgEquipData& from);

  inline MsgEquipData& operator=(const MsgEquipData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgEquipData& default_instance();

  void Swap(MsgEquipData* other);

  // implements Message ----------------------------------------------

  inline MsgEquipData* New() const { return New(NULL); }

  MsgEquipData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgEquipData& from);
  void MergeFrom(const MsgEquipData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgEquipData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // required int32 equip_id = 2;
  bool has_equip_id() const;
  void clear_equip_id();
  static const int kEquipIdFieldNumber = 2;
  ::google::protobuf::int32 equip_id() const;
  void set_equip_id(::google::protobuf::int32 value);

  // required int32 level = 3;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 3;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // required bool equipped = 4;
  bool has_equipped() const;
  void clear_equipped();
  static const int kEquippedFieldNumber = 4;
  bool equipped() const;
  void set_equipped(bool value);

  // required int32 client_save_flag = 5;
  bool has_client_save_flag() const;
  void clear_client_save_flag();
  static const int kClientSaveFlagFieldNumber = 5;
  ::google::protobuf::int32 client_save_flag() const;
  void set_client_save_flag(::google::protobuf::int32 value);

  // required int32 count = 6;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 6;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgEquipData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_equip_id();
  inline void clear_has_equip_id();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_equipped();
  inline void clear_has_equipped();
  inline void set_has_client_save_flag();
  inline void clear_has_client_save_flag();
  inline void set_has_count();
  inline void clear_has_count();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::int32 equip_id_;
  ::google::protobuf::int32 level_;
  bool equipped_;
  ::google::protobuf::int32 client_save_flag_;
  ::google::protobuf::int32 count_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgEquipData* default_instance_;
};
// -------------------------------------------------------------------

class MsgIntPair : public ::google::protobuf::Message {
 public:
  MsgIntPair();
  virtual ~MsgIntPair();

  MsgIntPair(const MsgIntPair& from);

  inline MsgIntPair& operator=(const MsgIntPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgIntPair& default_instance();

  void Swap(MsgIntPair* other);

  // implements Message ----------------------------------------------

  inline MsgIntPair* New() const { return New(NULL); }

  MsgIntPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgIntPair& from);
  void MergeFrom(const MsgIntPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgIntPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 number_1 = 1;
  bool has_number_1() const;
  void clear_number_1();
  static const int kNumber1FieldNumber = 1;
  ::google::protobuf::int32 number_1() const;
  void set_number_1(::google::protobuf::int32 value);

  // required int32 number_2 = 2;
  bool has_number_2() const;
  void clear_number_2();
  static const int kNumber2FieldNumber = 2;
  ::google::protobuf::int32 number_2() const;
  void set_number_2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgIntPair)
 private:
  inline void set_has_number_1();
  inline void clear_has_number_1();
  inline void set_has_number_2();
  inline void clear_has_number_2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 number_1_;
  ::google::protobuf::int32 number_2_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgIntPair* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgHeroData

// required uint64 account = 1;
inline bool MsgHeroData::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgHeroData::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgHeroData::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgHeroData::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
inline ::google::protobuf::uint64 MsgHeroData::account() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.account)
  return account_;
}
inline void MsgHeroData::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.account)
}

// required uint32 level = 2;
inline bool MsgHeroData::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgHeroData::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgHeroData::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgHeroData::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 MsgHeroData::level() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.level)
  return level_;
}
inline void MsgHeroData::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.level)
}

// required string name = 3;
inline bool MsgHeroData::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgHeroData::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgHeroData::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgHeroData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& MsgHeroData::name() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgHeroData::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.MsgHeroData.name)
}
inline void MsgHeroData::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.MsgHeroData.name)
}
inline void MsgHeroData::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.MsgHeroData.name)
}
inline ::std::string* MsgHeroData::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:message.MsgHeroData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgHeroData::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgHeroData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:message.MsgHeroData.name)
}

// required int32 action_point = 4;
inline bool MsgHeroData::has_action_point() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgHeroData::set_has_action_point() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgHeroData::clear_has_action_point() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgHeroData::clear_action_point() {
  action_point_ = 0;
  clear_has_action_point();
}
inline ::google::protobuf::int32 MsgHeroData::action_point() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.action_point)
  return action_point_;
}
inline void MsgHeroData::set_action_point(::google::protobuf::int32 value) {
  set_has_action_point();
  action_point_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.action_point)
}

// required int32 diamand = 5;
inline bool MsgHeroData::has_diamand() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgHeroData::set_has_diamand() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgHeroData::clear_has_diamand() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgHeroData::clear_diamand() {
  diamand_ = 0;
  clear_has_diamand();
}
inline ::google::protobuf::int32 MsgHeroData::diamand() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.diamand)
  return diamand_;
}
inline void MsgHeroData::set_diamand(::google::protobuf::int32 value) {
  set_has_diamand();
  diamand_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.diamand)
}

// required int32 gold = 6;
inline bool MsgHeroData::has_gold() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgHeroData::set_has_gold() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgHeroData::clear_has_gold() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgHeroData::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 MsgHeroData::gold() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.gold)
  return gold_;
}
inline void MsgHeroData::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.gold)
}

// -------------------------------------------------------------------

// MsgEquipData

// required uint64 id = 1;
inline bool MsgEquipData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgEquipData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgEquipData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgEquipData::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 MsgEquipData::id() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.id)
  return id_;
}
inline void MsgEquipData::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.id)
}

// required int32 equip_id = 2;
inline bool MsgEquipData::has_equip_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgEquipData::set_has_equip_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgEquipData::clear_has_equip_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgEquipData::clear_equip_id() {
  equip_id_ = 0;
  clear_has_equip_id();
}
inline ::google::protobuf::int32 MsgEquipData::equip_id() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.equip_id)
  return equip_id_;
}
inline void MsgEquipData::set_equip_id(::google::protobuf::int32 value) {
  set_has_equip_id();
  equip_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.equip_id)
}

// required int32 level = 3;
inline bool MsgEquipData::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgEquipData::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgEquipData::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgEquipData::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 MsgEquipData::level() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.level)
  return level_;
}
inline void MsgEquipData::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.level)
}

// required bool equipped = 4;
inline bool MsgEquipData::has_equipped() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgEquipData::set_has_equipped() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgEquipData::clear_has_equipped() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgEquipData::clear_equipped() {
  equipped_ = false;
  clear_has_equipped();
}
inline bool MsgEquipData::equipped() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.equipped)
  return equipped_;
}
inline void MsgEquipData::set_equipped(bool value) {
  set_has_equipped();
  equipped_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.equipped)
}

// required int32 client_save_flag = 5;
inline bool MsgEquipData::has_client_save_flag() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgEquipData::set_has_client_save_flag() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgEquipData::clear_has_client_save_flag() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgEquipData::clear_client_save_flag() {
  client_save_flag_ = 0;
  clear_has_client_save_flag();
}
inline ::google::protobuf::int32 MsgEquipData::client_save_flag() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.client_save_flag)
  return client_save_flag_;
}
inline void MsgEquipData::set_client_save_flag(::google::protobuf::int32 value) {
  set_has_client_save_flag();
  client_save_flag_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.client_save_flag)
}

// required int32 count = 6;
inline bool MsgEquipData::has_count() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgEquipData::set_has_count() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgEquipData::clear_has_count() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgEquipData::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 MsgEquipData::count() const {
  // @@protoc_insertion_point(field_get:message.MsgEquipData.count)
  return count_;
}
inline void MsgEquipData::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:message.MsgEquipData.count)
}

// -------------------------------------------------------------------

// MsgIntPair

// required int32 number_1 = 1;
inline bool MsgIntPair::has_number_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgIntPair::set_has_number_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgIntPair::clear_has_number_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgIntPair::clear_number_1() {
  number_1_ = 0;
  clear_has_number_1();
}
inline ::google::protobuf::int32 MsgIntPair::number_1() const {
  // @@protoc_insertion_point(field_get:message.MsgIntPair.number_1)
  return number_1_;
}
inline void MsgIntPair::set_number_1(::google::protobuf::int32 value) {
  set_has_number_1();
  number_1_ = value;
  // @@protoc_insertion_point(field_set:message.MsgIntPair.number_1)
}

// required int32 number_2 = 2;
inline bool MsgIntPair::has_number_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgIntPair::set_has_number_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgIntPair::clear_has_number_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgIntPair::clear_number_2() {
  number_2_ = 0;
  clear_has_number_2();
}
inline ::google::protobuf::int32 MsgIntPair::number_2() const {
  // @@protoc_insertion_point(field_get:message.MsgIntPair.number_2)
  return number_2_;
}
inline void MsgIntPair::set_number_2(::google::protobuf::int32 value) {
  set_has_number_2();
  number_2_ = value;
  // @@protoc_insertion_point(field_set:message.MsgIntPair.number_2)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::message::HeroErrorCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::message::HeroErrorCode>() {
  return ::message::HeroErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
