// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dream_hero.proto

#ifndef PROTOBUF_dream_5fhero_2eproto__INCLUDED
#define PROTOBUF_dream_5fhero_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dream_5fhero_2eproto();
void protobuf_AssignDesc_dream_5fhero_2eproto();
void protobuf_ShutdownFile_dream_5fhero_2eproto();

class S2CMsgHeroInit;
class S2CMsgHeroEquip;
class S2CMsgEquipInit;

// ===================================================================

class S2CMsgHeroInit : public ::google::protobuf::Message {
 public:
  S2CMsgHeroInit();
  virtual ~S2CMsgHeroInit();

  S2CMsgHeroInit(const S2CMsgHeroInit& from);

  inline S2CMsgHeroInit& operator=(const S2CMsgHeroInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgHeroInit& default_instance();

  void Swap(S2CMsgHeroInit* other);

  // implements Message ----------------------------------------------

  inline S2CMsgHeroInit* New() const { return New(NULL); }

  S2CMsgHeroInit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgHeroInit& from);
  void MergeFrom(const S2CMsgHeroInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgHeroInit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.MsgHeroData hero = 1;
  bool has_hero() const;
  void clear_hero();
  static const int kHeroFieldNumber = 1;
  const ::message::MsgHeroData& hero() const;
  ::message::MsgHeroData* mutable_hero();
  ::message::MsgHeroData* release_hero();
  void set_allocated_hero(::message::MsgHeroData* hero);

  // @@protoc_insertion_point(class_scope:message.S2CMsgHeroInit)
 private:
  inline void set_has_hero();
  inline void clear_has_hero();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::MsgHeroData* hero_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgHeroInit* default_instance_;
};
// -------------------------------------------------------------------

class S2CMsgHeroEquip : public ::google::protobuf::Message {
 public:
  S2CMsgHeroEquip();
  virtual ~S2CMsgHeroEquip();

  S2CMsgHeroEquip(const S2CMsgHeroEquip& from);

  inline S2CMsgHeroEquip& operator=(const S2CMsgHeroEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgHeroEquip& default_instance();

  void Swap(S2CMsgHeroEquip* other);

  // implements Message ----------------------------------------------

  inline S2CMsgHeroEquip* New() const { return New(NULL); }

  S2CMsgHeroEquip* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgHeroEquip& from);
  void MergeFrom(const S2CMsgHeroEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgHeroEquip* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .message.MsgEquipData equips = 1;
  int equips_size() const;
  void clear_equips();
  static const int kEquipsFieldNumber = 1;
  const ::message::MsgEquipData& equips(int index) const;
  ::message::MsgEquipData* mutable_equips(int index);
  ::message::MsgEquipData* add_equips();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >&
      equips() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >*
      mutable_equips();

  // required bool end = 2;
  bool has_end() const;
  void clear_end();
  static const int kEndFieldNumber = 2;
  bool end() const;
  void set_end(bool value);

  // required bool begin = 3;
  bool has_begin() const;
  void clear_begin();
  static const int kBeginFieldNumber = 3;
  bool begin() const;
  void set_begin(bool value);

  // @@protoc_insertion_point(class_scope:message.S2CMsgHeroEquip)
 private:
  inline void set_has_end();
  inline void clear_has_end();
  inline void set_has_begin();
  inline void clear_has_begin();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData > equips_;
  bool end_;
  bool begin_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgHeroEquip* default_instance_;
};
// -------------------------------------------------------------------

class S2CMsgEquipInit : public ::google::protobuf::Message {
 public:
  S2CMsgEquipInit();
  virtual ~S2CMsgEquipInit();

  S2CMsgEquipInit(const S2CMsgEquipInit& from);

  inline S2CMsgEquipInit& operator=(const S2CMsgEquipInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgEquipInit& default_instance();

  void Swap(S2CMsgEquipInit* other);

  // implements Message ----------------------------------------------

  inline S2CMsgEquipInit* New() const { return New(NULL); }

  S2CMsgEquipInit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgEquipInit& from);
  void MergeFrom(const S2CMsgEquipInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgEquipInit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.S2CMsgHeroEquip equip = 1;
  bool has_equip() const;
  void clear_equip();
  static const int kEquipFieldNumber = 1;
  const ::message::S2CMsgHeroEquip& equip() const;
  ::message::S2CMsgHeroEquip* mutable_equip();
  ::message::S2CMsgHeroEquip* release_equip();
  void set_allocated_equip(::message::S2CMsgHeroEquip* equip);

  // @@protoc_insertion_point(class_scope:message.S2CMsgEquipInit)
 private:
  inline void set_has_equip();
  inline void clear_has_equip();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::S2CMsgHeroEquip* equip_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgEquipInit* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// S2CMsgHeroInit

// required .message.MsgHeroData hero = 1;
inline bool S2CMsgHeroInit::has_hero() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CMsgHeroInit::set_has_hero() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CMsgHeroInit::clear_has_hero() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CMsgHeroInit::clear_hero() {
  if (hero_ != NULL) hero_->::message::MsgHeroData::Clear();
  clear_has_hero();
}
inline const ::message::MsgHeroData& S2CMsgHeroInit::hero() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroInit.hero)
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::message::MsgHeroData* S2CMsgHeroInit::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) {
    hero_ = new ::message::MsgHeroData;
  }
  // @@protoc_insertion_point(field_mutable:message.S2CMsgHeroInit.hero)
  return hero_;
}
inline ::message::MsgHeroData* S2CMsgHeroInit::release_hero() {
  clear_has_hero();
  ::message::MsgHeroData* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void S2CMsgHeroInit::set_allocated_hero(::message::MsgHeroData* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
  // @@protoc_insertion_point(field_set_allocated:message.S2CMsgHeroInit.hero)
}

// -------------------------------------------------------------------

// S2CMsgHeroEquip

// repeated .message.MsgEquipData equips = 1;
inline int S2CMsgHeroEquip::equips_size() const {
  return equips_.size();
}
inline void S2CMsgHeroEquip::clear_equips() {
  equips_.Clear();
}
inline const ::message::MsgEquipData& S2CMsgHeroEquip::equips(int index) const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.equips)
  return equips_.Get(index);
}
inline ::message::MsgEquipData* S2CMsgHeroEquip::mutable_equips(int index) {
  // @@protoc_insertion_point(field_mutable:message.S2CMsgHeroEquip.equips)
  return equips_.Mutable(index);
}
inline ::message::MsgEquipData* S2CMsgHeroEquip::add_equips() {
  // @@protoc_insertion_point(field_add:message.S2CMsgHeroEquip.equips)
  return equips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >&
S2CMsgHeroEquip::equips() const {
  // @@protoc_insertion_point(field_list:message.S2CMsgHeroEquip.equips)
  return equips_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >*
S2CMsgHeroEquip::mutable_equips() {
  // @@protoc_insertion_point(field_mutable_list:message.S2CMsgHeroEquip.equips)
  return &equips_;
}

// required bool end = 2;
inline bool S2CMsgHeroEquip::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CMsgHeroEquip::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CMsgHeroEquip::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CMsgHeroEquip::clear_end() {
  end_ = false;
  clear_has_end();
}
inline bool S2CMsgHeroEquip::end() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.end)
  return end_;
}
inline void S2CMsgHeroEquip::set_end(bool value) {
  set_has_end();
  end_ = value;
  // @@protoc_insertion_point(field_set:message.S2CMsgHeroEquip.end)
}

// required bool begin = 3;
inline bool S2CMsgHeroEquip::has_begin() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2CMsgHeroEquip::set_has_begin() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2CMsgHeroEquip::clear_has_begin() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2CMsgHeroEquip::clear_begin() {
  begin_ = false;
  clear_has_begin();
}
inline bool S2CMsgHeroEquip::begin() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.begin)
  return begin_;
}
inline void S2CMsgHeroEquip::set_begin(bool value) {
  set_has_begin();
  begin_ = value;
  // @@protoc_insertion_point(field_set:message.S2CMsgHeroEquip.begin)
}

// -------------------------------------------------------------------

// S2CMsgEquipInit

// required .message.S2CMsgHeroEquip equip = 1;
inline bool S2CMsgEquipInit::has_equip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CMsgEquipInit::set_has_equip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CMsgEquipInit::clear_has_equip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CMsgEquipInit::clear_equip() {
  if (equip_ != NULL) equip_->::message::S2CMsgHeroEquip::Clear();
  clear_has_equip();
}
inline const ::message::S2CMsgHeroEquip& S2CMsgEquipInit::equip() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgEquipInit.equip)
  return equip_ != NULL ? *equip_ : *default_instance_->equip_;
}
inline ::message::S2CMsgHeroEquip* S2CMsgEquipInit::mutable_equip() {
  set_has_equip();
  if (equip_ == NULL) {
    equip_ = new ::message::S2CMsgHeroEquip;
  }
  // @@protoc_insertion_point(field_mutable:message.S2CMsgEquipInit.equip)
  return equip_;
}
inline ::message::S2CMsgHeroEquip* S2CMsgEquipInit::release_equip() {
  clear_has_equip();
  ::message::S2CMsgHeroEquip* temp = equip_;
  equip_ = NULL;
  return temp;
}
inline void S2CMsgEquipInit::set_allocated_equip(::message::S2CMsgHeroEquip* equip) {
  delete equip_;
  equip_ = equip;
  if (equip) {
    set_has_equip();
  } else {
    clear_has_equip();
  }
  // @@protoc_insertion_point(field_set_allocated:message.S2CMsgEquipInit.equip)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dream_5fhero_2eproto__INCLUDED
